backend:
  name: git-gateway
  branch: main
media_folder: static/images/
public_folder: /images/
# Support Hugo page bundles that puts index.md and images in folders named by slug
locale: 'pt'
collections: # A list of collections the CMS should be able to edit
  - name: "Páginas"
    editor:
      preview: false
    label: "Páginas"
    files:
      - file: "content/_index.md"
        label: "Landing"
        name: "landing"
        fields:
          - { label: "Texto Maior", name: "title", widget: "string" }
          - { label: "Texto Menor", name: "description", widget: "string" }
          - { label: "Frase 1", name: "flavor_textA", widget: "string" }
          - { label: "Frase 2", name: "flavor_textB", widget: "string" }
          - { label: "Frase 3", name: "flavor_textC", widget: "string", required: false }
          - { label: "Imagem", name: "hero_img", widget: "image" }
          - { label: "Bio", name: "body", widget: "markdown"}
      - file: "content/portfolio/_index.md"
        label: "Portfólio"
        name: "portfolio"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Legenda", name: "description", widget: "markdown" }
      - file: "content/seletiva/_index.md"
        label: "Seletiva"
        name: "seletiva"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "body", widget: "markdown" }
      - file: "content/equipe/_index.md"
        label: "Equipe"
        name: "equipe"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Legenda", name: "description", widget: "markdown" }
  - name: "portfolio" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Jobs" # Used in the UI, ie.: "New Post"
    label_singular: "Job"
    folder: "content/portfolio/job" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Job", name: "title", widget: "string" }
      - { label: "Tipo", name: "job_Type", widget: "string" }
      - { label: "Cliente", name: "cliente", widget: "string" }
      - { label: "Direção de Arte:", name: "AuthorA", widget: "string", required: false }
      - { label: "Redação:", name: "AuthorB", widget: "string", required: false }
      - { label: "Produção", name: "AuthorC", widget: "string", required: false }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Conteúdo", name: "body", widget: "markdown"}
  - name: "Equipe" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pessoas" # Used in the UI, ie.: "New Post"
    label_singular: "Pessoa"
    folder: "content/equipe/pessoas" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Área", name: "area", widget: "string" }
      - { label: "Foto", name: "foto", widget: "image" }
