backend:
  name: git-gateway
  branch: main
media_folder: static/images/
public_folder: /images/
# Support Hugo page bundles that puts index.md and images in folders named by slug
path: "{{slug}}/_index"
locale: 'pt'
collections:
  - name: "Settings"
    label: "Home"
    folder: "content/_index.md"
    create: false
    fields:
      - { label: "Texto Maior", name: "title", widget: "string" }
      - { label: "Texto Menor", name: "description", widget: "string" }
      - { label: "Frase 1", name: "flavor_textA", widget: "string" }
      - { label: "Frase 2", name: "flavor_textB", widget: "string" }
      - { label: "Frase 3", name: "flavor_textC", widget: "string", required: "false" }
      - { label: "Imagem", name: "hero_img", widget: "image" }
      - { label: "Bio", name: "body", widget: "markdown"}

    label: "Texto Portfólio"
    folder: "content/portfolio/_index.md"
    create: false
    fields:
      - { label: "Texto Maior", name: "title", widget: "string" }
      - { label: "Texto Menor", name: "description", widget: "string" }

  - name: "Portfólio"
    label: "Portfólio"
    folder: "content/portfolio/"
    create: true
    fields:
      - { label: "Job", name: "title", widget: "string" }
      - { label: "Tipo", name: "job_Type", widget: "string" }
      - { label: "Cor", name: "color", widget: "color" }
      - { label: "Cliente", name: "cliente", widget: "string" }
      - { label: "Direção de Arte:", name: "AuthorA", widget: "string" }
      - { label: "Redação:", name: "AuthorB", widget: "string" , required: "false"}      
      - { label: "Produção", name: "AuthorC", widget: "string" , required: "false"}
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Conteúdo", name: "body", widget: "markdown"}
