backend:
  name: git-gateway
  branch: main
media_folder: static/images/
public_folder: /images/
# Support Hugo page bundles that puts index.md and images in folders named by slug
path: "{{slug}}/_index"
locale: 'pt'
collections:
  - name: "Home"
    label: "Home"
    folder: "content/"
    create: false
    fields:
      - { label: "Texto Maior", name: "Title", widget: "string" }
      - { label: "Texto Menor", name: "Description", widget: "string" }
      - { label: "Frase 1", name: "Flavor_textA", widget: "string" }
      - { label: "Frase 2", name: "Flavor_textB", widget: "string" }
      - { label: "Frase 3", name: "Flavor_textC", widget: "string" }
      - { label: "Imagem", name: "Hero_img", widget: "image" }
      - { label: "Bio", name: "body", widget: "markdown"}
