name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 12 * * wed' # At 12:00 on Wednesday
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/63e85b81cc473a2e93203339